version: "3.7"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=uberadmin
      - MYSQL_PASSWORD=uberadminpass
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
    volumes: 
      - ./data:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks: 
      - uber-eats

  auth:
    depends_on: 
      - mysqldb
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 7000:3000
    volumes: 
      - type: bind
        source: ./auth
        target: /app
      - type: bind
        source: ./auth/node_modules
        target: /app/node_modules
    restart: unless-stopped
    networks: 
      - uber-eats

  restaurant:
    depends_on: 
      - mysqldb
    build:
      context: ./restaurant
      dockerfile: Dockerfile
    ports:
      - 7001:3000
    volumes: 
      - type: bind
        source: ./restaurant
        target: /app
      - type: bind
        source: ./restaurant/node_modules
        target: /app/node_modules
    restart: unless-stopped
    networks: 
      - uber-eats

  customer:
    depends_on: 
      - mysqldb
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - 7002:3000
    volumes: 
      - type: bind
        source: ./customer
        target: /app
      - type: bind
        source: ./customer/node_modules
        target: /app/node_modules
    restart: unless-stopped
    networks: 
      - uber-eats

  order:
    depends_on: 
      - mysqldb
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - 7003:3000
    volumes: 
      - type: bind
        source: ./order
        target: /app
      - type: bind
        source: ./order/node_modules
        target: /app/node_modules
    restart: unless-stopped
    networks: 
      - uber-eats

  nginx:
    depends_on: 
      - mysqldb
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes: 
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks: 
      - uber-eats

networks: 
  uber-eats: