export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_MEDIUM = 'CREATE_CUSTOMER_MEDIUM';

export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const CREATE_RESTAURANT_MEDIA = 'CREATE_RESTAURANT_MEDIA';

export const NOTIFY = 'NOTIFY';
