export const FETCH_AUTH_CUSTOMER = 'FETCH_AUTH_CUSTOMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const CREATE_CUSTOMER_MEDIUM = 'CREATE_CUSTOMER_MEDIUM';
export const CLEAR_CUSTOMER_MEDIUM = 'CLEAR_CUSTOMER_MEDIUM';

export const FETCH_AUTH_RESTAURANT = 'FETCH_AUTH_RESTAURANT';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const CREATE_RESTAURANT_MEDIA = 'CREATE_RESTAURANT_MEDIA';
export const CLEAR_RESTAURANT_MEDIA = 'CLEAR_RESTAURANT_MEDIA';

export const CREATE_RESTAURANT_DISH = 'CREATE_RESTAURANT_DISH';
export const UPDATE_RESTAURANT_DISH = 'UPDATE_RESTAURANT_DISH';
export const CLEAR_DISH_MEDIA = 'CLEAR_DISH_MEDIA';
export const CREATE_DISH_MEDIA = 'CREATE_DISH_MEDIA';

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';

export const NOTIFY = 'NOTIFY';
