CREATE DATABASE IF NOT EXISTS `auth`;
CREATE DATABASE IF NOT EXISTS `restaurant`;
CREATE DATABASE IF NOT EXISTS `customer`;
CREATE DATABASE IF NOT EXISTS `order`;

GRANT ALL PRIVILEGES ON *.* TO 'uberadmin'@'%';