---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: ubereats
    tier: message-broker
    svc: zookeeper
spec:
  selector:
    matchLabels:
      app: ubereats
      tier: message-broker
      svc: zookeeper
  template:
    metadata:
      labels:
        app: ubereats
        tier: message-broker
        svc: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 2181
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: 'yes'
          - name: ZOOKEEPER_CLIENT_PORT
            value: '2181'

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: ubereats
    tier: message-broker
    svc: zookeeper
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: ubereats
    tier: message-broker
    svc: kafka
spec:
  selector:
    matchLabels:
      app: ubereats
      tier: message-broker
      svc: kafka
  template:
    metadata:
      labels:
        app: ubereats
        tier: message-broker
        svc: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: ubereats
    tier: message-broker
    svc: kafka
  ports:
  - port: 9092
    targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-backend
spec:
  selector:
    matchLabels:
      app: ubereats
      tier: message-broker
      svc: kafka-backend
  template:
    metadata:
      labels:
        app: ubereats
        tier: message-broker
        svc: kafka-backend
    spec:
      containers:
      - name: kafka-backend
        image: hetpatel572/ubereats-kafka-backend
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-backend
spec:
  selector:
    app: ubereats
    tier: message-broker
    svc: kafka-backend
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
